package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetStaticAssetVersionsReader is a Reader for the GetStaticAssetVersions structure.
type GetStaticAssetVersionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetStaticAssetVersionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetStaticAssetVersionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetStaticAssetVersionsOK creates a GetStaticAssetVersionsOK with default headers values
func NewGetStaticAssetVersionsOK() *GetStaticAssetVersionsOK {
	return &GetStaticAssetVersionsOK{}
}

/*GetStaticAssetVersionsOK handles this case with default header values.

list of versions
*/
type GetStaticAssetVersionsOK struct {
	Payload []string
}

func (o *GetStaticAssetVersionsOK) Error() string {
	return fmt.Sprintf("[GET /api/lol/static-data/{region}/v1.2/versions][%d] getStaticAssetVersionsOK  %+v", 200, o.Payload)
}

func (o *GetStaticAssetVersionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
