package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/nmonterroso/lolchest.win/riotapi/models"
)

// GetSummonerChampionMasteryReader is a Reader for the GetSummonerChampionMastery structure.
type GetSummonerChampionMasteryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetSummonerChampionMasteryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetSummonerChampionMasteryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetSummonerChampionMasteryOK creates a GetSummonerChampionMasteryOK with default headers values
func NewGetSummonerChampionMasteryOK() *GetSummonerChampionMasteryOK {
	return &GetSummonerChampionMasteryOK{}
}

/*GetSummonerChampionMasteryOK handles this case with default header values.

list of champion mastery data for a summoner
*/
type GetSummonerChampionMasteryOK struct {
	Payload []*models.ChampionMasteryDto
}

func (o *GetSummonerChampionMasteryOK) Error() string {
	return fmt.Sprintf("[GET /championmastery/location/{platformId}/player/{summonerId}/champions][%d] getSummonerChampionMasteryOK  %+v", 200, o.Payload)
}

func (o *GetSummonerChampionMasteryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
