package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/nmonterroso/lolchest.win/riotapi/models"
)

// GetSummonerProfileReader is a Reader for the GetSummonerProfile structure.
type GetSummonerProfileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetSummonerProfileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetSummonerProfileOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetSummonerProfileOK creates a GetSummonerProfileOK with default headers values
func NewGetSummonerProfileOK() *GetSummonerProfileOK {
	return &GetSummonerProfileOK{}
}

/*GetSummonerProfileOK handles this case with default header values.

list of summoner profile data
*/
type GetSummonerProfileOK struct {
	Payload GetSummonerProfileOKBodyBody
}

func (o *GetSummonerProfileOK) Error() string {
	return fmt.Sprintf("[GET /api/lol/{region}/v1.4/summoner/by-name/{summonerNames}][%d] getSummonerProfileOK  %+v", 200, o.Payload)
}

func (o *GetSummonerProfileOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetSummonerProfileOKBodyBody get summoner profile o k body body

swagger:model GetSummonerProfileOKBodyBody
*/
type GetSummonerProfileOKBodyBody map[string]models.SummonerDto

// Validate validates this get summoner profile o k body body
func (o GetSummonerProfileOKBodyBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.Required("getSummonerProfileOK", "body", o); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
