package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetStaticAssetVersionsParams creates a new GetStaticAssetVersionsParams object
// with the default values initialized.
func NewGetStaticAssetVersionsParams() *GetStaticAssetVersionsParams {
	var (
		regionDefault string = string("na")
	)
	return &GetStaticAssetVersionsParams{
		Region: regionDefault,
	}
}

/*GetStaticAssetVersionsParams contains all the parameters to send to the API endpoint
for the get static asset versions operation typically these are written to a http.Request
*/
type GetStaticAssetVersionsParams struct {

	/*Region*/
	Region string
}

// WithRegion adds the region to the get static asset versions params
func (o *GetStaticAssetVersionsParams) WithRegion(Region string) *GetStaticAssetVersionsParams {
	o.Region = Region
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetStaticAssetVersionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	var res []error

	// path param region
	if err := r.SetPathParam("region", o.Region); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
