package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSummonerChampionMasteryParams creates a new GetSummonerChampionMasteryParams object
// with the default values initialized.
func NewGetSummonerChampionMasteryParams() *GetSummonerChampionMasteryParams {
	var (
		platformIdDefault string = string("na1")
	)
	return &GetSummonerChampionMasteryParams{
		PlatformID: platformIdDefault,
	}
}

/*GetSummonerChampionMasteryParams contains all the parameters to send to the API endpoint
for the get summoner champion mastery operation typically these are written to a http.Request
*/
type GetSummonerChampionMasteryParams struct {

	/*PlatformID*/
	PlatformID string
	/*SummonerID*/
	SummonerID int64
}

// WithPlatformID adds the platformId to the get summoner champion mastery params
func (o *GetSummonerChampionMasteryParams) WithPlatformID(PlatformID string) *GetSummonerChampionMasteryParams {
	o.PlatformID = PlatformID
	return o
}

// WithSummonerID adds the summonerId to the get summoner champion mastery params
func (o *GetSummonerChampionMasteryParams) WithSummonerID(SummonerID int64) *GetSummonerChampionMasteryParams {
	o.SummonerID = SummonerID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetSummonerChampionMasteryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	var res []error

	// path param platformId
	if err := r.SetPathParam("platformId", o.PlatformID); err != nil {
		return err
	}

	// path param summonerId
	if err := r.SetPathParam("summonerId", swag.FormatInt64(o.SummonerID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
