package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/nmonterroso/lolchest.win/riotapi/models"
)

// GetChampionDataReader is a Reader for the GetChampionData structure.
type GetChampionDataReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetChampionDataReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetChampionDataOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetChampionDataOK creates a GetChampionDataOK with default headers values
func NewGetChampionDataOK() *GetChampionDataOK {
	return &GetChampionDataOK{}
}

/*GetChampionDataOK handles this case with default header values.

all champion static data
*/
type GetChampionDataOK struct {
	Payload *models.ChampionListDto
}

func (o *GetChampionDataOK) Error() string {
	return fmt.Sprintf("[GET /api/lol/static-data/{region}/v1.2/champion][%d] getChampionDataOK  %+v", 200, o.Payload)
}

func (o *GetChampionDataOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ChampionListDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
