package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

/*ImageDto image dto

swagger:model ImageDto
*/
type ImageDto struct {

	/* full

	Required: true
	*/
	Full *string `json:"full"`
}

// Validate validates this image dto
func (m *ImageDto) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFull(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImageDto) validateFull(formats strfmt.Registry) error {

	if err := validate.Required("full", "body", m.Full); err != nil {
		return err
	}

	return nil
}
