package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/nmonterroso/lolchest.win/models"
)

/*GetSummonerOK summoner data

swagger:response getSummonerOK
*/
type GetSummonerOK struct {

	// In: body
	Payload *models.Summoner `json:"body,omitempty"`
}

// NewGetSummonerOK creates GetSummonerOK with default headers values
func NewGetSummonerOK() *GetSummonerOK {
	return &GetSummonerOK{}
}

// WithPayload adds the payload to the get summoner o k response
func (o *GetSummonerOK) WithPayload(payload *models.Summoner) *GetSummonerOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get summoner o k response
func (o *GetSummonerOK) SetPayload(payload *models.Summoner) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSummonerOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetSummonerDefault Unexpected error

swagger:response getSummonerDefault
*/
type GetSummonerDefault struct {
	_statusCode int

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetSummonerDefault creates GetSummonerDefault with default headers values
func NewGetSummonerDefault(code int) *GetSummonerDefault {
	if code <= 0 {
		code = 500
	}

	return &GetSummonerDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get summoner default response
func (o *GetSummonerDefault) WithStatusCode(code int) *GetSummonerDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get summoner default response
func (o *GetSummonerDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get summoner default response
func (o *GetSummonerDefault) WithPayload(payload *models.Error) *GetSummonerDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get summoner default response
func (o *GetSummonerDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSummonerDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
