package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/nmonterroso/lolchest.win/riotapi/client/operations"
)

// Default riot HTTP client.
var Default = NewHTTPClient(nil)

// NewHTTPClient creates a new riot HTTP client.
func NewHTTPClient(formats strfmt.Registry) *Riot {
	if formats == nil {
		formats = strfmt.Default
	}
	transport := httptransport.New("global.api.pvp.net", "/", []string{"https"})
	return New(transport, formats)
}

// New creates a new riot client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Riot {
	cli := new(Riot)
	cli.Transport = transport

	cli.Operations = operations.New(transport, formats)

	return cli
}

// Riot is a client for riot
type Riot struct {
	Operations *operations.Client

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *Riot) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport

	c.Operations.SetTransport(transport)

}
