package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

/*ChampionData champion data

swagger:model ChampionData
*/
type ChampionData struct {

	/* icon Url

	Required: true
	*/
	IconURL *string `json:"iconUrl"`

	/* id

	Required: true
	*/
	ID *int64 `json:"id"`

	/* name

	Required: true
	*/
	Name *string `json:"name"`
}

// Validate validates this champion data
func (m *ChampionData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateIconURL(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ChampionData) validateIconURL(formats strfmt.Registry) error {

	if err := validate.Required("iconUrl", "body", m.IconURL); err != nil {
		return err
	}

	return nil
}

func (m *ChampionData) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *ChampionData) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}
