package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

/*Summoner summoner

swagger:model Summoner
*/
type Summoner struct {

	/* champ data

	Required: true
	*/
	ChampData []*SummonerChampChestData `json:"champData"`

	/* id

	Required: true
	*/
	ID *int64 `json:"id"`

	/* name

	Required: true
	*/
	Name *string `json:"name"`

	/* profile icon Url

	Required: true
	*/
	ProfileIconURL *string `json:"profileIconUrl"`
}

// Validate validates this summoner
func (m *Summoner) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateChampData(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateProfileIconURL(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Summoner) validateChampData(formats strfmt.Registry) error {

	if err := validate.Required("champData", "body", m.ChampData); err != nil {
		return err
	}

	return nil
}

func (m *Summoner) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *Summoner) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *Summoner) validateProfileIconURL(formats strfmt.Registry) error {

	if err := validate.Required("profileIconUrl", "body", m.ProfileIconURL); err != nil {
		return err
	}

	return nil
}
